### ISSUE TITLE
Error during Windows build

### ISSUE THREAD

**Issue by victorypoint** [vincent290587/ZwiftWorkoutConverter#1]
Unable to find suitable Visual Studio toolchain. Please run `flutter doctor` for more details.

**Comment by vincent290587** [comment]
Please follow the flutter windows requirements to build the program for Windows:

https://docs.flutter.dev/development/platform-integration/desktop

https://stackoverflow.com/questions/60334570/unable-to-find-suitable-visual-studio-toolchain-please-run-flutter-doctor-for
